// ================================================================
// FILE: backend/siem/models/Alert.js
// SIEM Alert schema — generated by rule engine from events
// ================================================================

const mongoose = require("mongoose");

const alertSchema = new mongoose.Schema({

  alertId: {
    type: String,
    default: () => `ALT-${Date.now()}-${Math.random().toString(36).slice(2, 7).toUpperCase()}`,
    unique: true,
    index: true,
  },

  // ── Classification ──
  title:       { type: String, required: true },
  description: { type: String, default: "" },
  category:    { type: String, required: true, index: true },
  ruleId:      { type: String, required: true },
  ruleName:    { type: String, required: true },

  // ── Severity ──
  severity: {
    type: Number,
    enum: [1, 2, 3, 4, 5],
    required: true,
    index: true,
  },
  severityLabel: {
    type: String,
    enum: ["INFO", "LOW", "MEDIUM", "HIGH", "CRITICAL"],
    required: true,
  },

  // ── Triggering events ──
  eventIds:   { type: [String], default: [] },
  eventCount: { type: Number, default: 1 },

  // ── Context ──
  target: {
    url:    { type: String, default: null },
    domain: { type: String, default: null },
    ip:     { type: String, default: null },
    email:  { type: String, default: null },
  },
  source: {
    ip:    { type: String, default: null },
    agent: { type: String, default: null },
  },

  // ── MITRE ──
  mitre: {
    tactic:    { type: String, default: null },
    technique: { type: String, default: null },
  },

  // ── Risk ──
  riskScore: { type: Number, min: 0, max: 100, default: 0 },

  // ── Correlation chain ──
  correlationId: { type: String, default: null, index: true },
  isCorrelated:  { type: Boolean, default: false }, // Part of an attack chain

  // ── Status & Workflow ──
  status: {
    type: String,
    enum: ["open", "investigating", "resolved", "false_positive", "suppressed"],
    default: "open",
    index: true,
  },

  // ── Timestamps ──
  firstSeen: { type: Date, default: Date.now },
  lastSeen:  { type: Date, default: Date.now },
  resolvedAt:{ type: Date, default: null },

  // ── Analyst notes ──
  notes:    { type: String, default: "" },
  assignee: { type: String, default: null },

  // ── Dedup key (prevents duplicate alerts for same event) ──
  dedupKey: { type: String, index: true },

  tags: { type: [String], default: [] },
});

alertSchema.index({ firstSeen: -1, severity: -1 });
alertSchema.index({ status: 1, severity: -1 });
alertSchema.index({ dedupKey: 1 }, { unique: true, sparse: true });

module.exports = mongoose.model("SiemAlert", alertSchema);